tigrisdata/tigris-client-java

- pom.xml
We will shortly use github workflows to publish. For now it is kept manual pre-release.
> Configure POM for SNAPSHOT (pre-release) publishing

- client/pom.xml
> Upgraded jackson-databind version to 2.13.2.2

- README.md
- client/src/main/java/com/tigrisdata/db/client/service/StandardTigrisDatabase.java
- client/src/main/java/com/tigrisdata/db/client/service/TigrisAsyncCollection.java
- client/src/main/java/com/tigrisdata/db/client/service/TigrisAsyncDatabase.java
- client/src/main/java/com/tigrisdata/db/client/service/TigrisDBAsyncClient.java
- client/src/main/java/com/tigrisdata/db/client/service/TigrisDBAsyncReader.java
- client/src/main/java/com/tigrisdata/db/client/service/TransactionAsyncSession.java
- client/src/main/java/com/tigrisdata/db/client/service/TransactionTigrisAsyncCollection.java
- client/src/test/java/com/tigrisdata/db/client/service/StandardTigrisDatabaseTest.java
#27 
- Added async interfaces.
- Removed AlterCollection API (as it is going to get removed from server soon).
TODO:
- refactor Fields for read and update.
> #27 Added initial async interfaces

- client/pom.xml
- client/src/main/java/com/tigrisdata/db/client/model/TypeConverter.java
- client/src/main/java/com/tigrisdata/db/client/model/UpdateFields.java
- client/src/main/java/com/tigrisdata/db/client/service/AbstractTigrisDBClient.java
- client/src/main/java/com/tigrisdata/db/client/service/StandardTigrisAsyncCollection.java
- client/src/main/java/com/tigrisdata/db/client/service/StandardTigrisAsyncDatabase.java
- client/src/main/java/com/tigrisdata/db/client/service/StandardTigrisCollection.java
- client/src/main/java/com/tigrisdata/db/client/service/StandardTigrisDBAsyncClient.java
- client/src/main/java/com/tigrisdata/db/client/service/StandardTigrisDBClient.java
- client/src/main/java/com/tigrisdata/db/client/service/StandardTransactionSession.java
- client/src/main/java/com/tigrisdata/db/client/service/TigrisAsyncDatabase.java
- client/src/main/java/com/tigrisdata/db/client/utils/Utilities.java
- client/src/test/java/com/tigrisdata/db/client/service/StandardTigrisAsyncDatabaseTest.java
- client/src/test/java/com/tigrisdata/db/client/service/StandardTigrisDBAsyncClientTest.java
- client/src/test/java/com/tigrisdata/db/client/service/TestUtils.java
- client/src/test/java/com/tigrisdata/db/client/utils/UtilitiesTest.java
#27 
TODO
- Implementation of Database, Collection, TransactionSession, TransactionalCollection. (in next PR)
> Added AsyncClient implementation

- client/src/main/java/com/tigrisdata/db/client/error/TigrisDBException.java
- client/src/main/java/com/tigrisdata/db/client/model/Filters.java
- client/src/main/java/com/tigrisdata/db/client/model/TigrisDBJSONSchema.java
- client/src/main/java/com/tigrisdata/db/client/model/TigrisDBSchema.java
- client/src/test/java/com/tigrisdata/db/client/service/StandardTigrisAsyncDatabaseTest.java
- client/src/test/java/com/tigrisdata/db/client/service/StandardTigrisDatabaseTest.java
- client/src/test/java/com/tigrisdata/db/client/service/TigrisDBJSONSchemaTest.java
- client/src/test/resources/test-schema.json
- Detailed error message
- long type filter support
- Construct schema from URL
> Detailed error message, long filter support, schema from URL

- code-generator/core/src/main/java/com/tigrisdata/tools/schema/TigrisDBObjectRule.java
- read collection name from "name" field of JSON schema.
- if the name is in plural, make it singular for Java class name.
> feat: Read collection name from 'name' field

- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncCollection.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisCollection.java
- client/src/main/java/com/tigrisdata/db/client/Utilities.java
- schema-generator/schema-generator-core/src/main/java/com/tigrisdata/tools/schema/core/DefaultModelToTigrisDBJsonSchema.java
- schema-generator/schema-generator-core/src/test/resources/testdata/ArrayFields.json
- schema-generator/schema-generator-core/src/test/resources/testdata/ArrayOfCustomType.json
- schema-generator/schema-generator-core/src/test/resources/testdata/BoxedTypes.json
- schema-generator/schema-generator-core/src/test/resources/testdata/ByteArrayMultiDimensional.json
- schema-generator/schema-generator-core/src/test/resources/testdata/CustomizedNestedObjectType.json
- schema-generator/schema-generator-core/src/test/resources/testdata/EnumTypes.json
- schema-generator/schema-generator-core/src/test/resources/testdata/NestedObjectTypes.json
- schema-generator/schema-generator-core/src/test/resources/testdata/PrimitiveTypes.json
- schema-generator/schema-generator-core/src/test/resources/testdata/TigrisCustomTypes.json
- Fixed the mechanism to get collection name.
- Fixed the typo in primary_keys field (primary_keys --> primary_key) in the schema.
> fix: primary_keys --> primary_key typo fixed

- client/pom.xml
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncDatabase.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisDatabase.java
- client/src/main/java/com/tigrisdata/db/client/TigrisDBJSONSchema.java
- client/src/main/java/com/tigrisdata/db/client/TigrisDBSchema.java
- client/src/main/java/com/tigrisdata/db/client/config/TigrisDBConfiguration.java
- client/src/test/java/com/tigrisdata/db/client/TigrisDBJSONSchemaTest.java
- client/src/test/java/com/tigrisdata/db/client/TypeConverterTest.java
- Configured default ObjectMapper to work with immutable objects.
- Fixed the schema name parsing.
> feat: Configured ObjectMapper to work with immutable objects

- client/src/main/java/com/tigrisdata/db/client/Messages.java
- client/src/main/java/com/tigrisdata/db/client/ServerMetadata.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncClient.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisClient.java
- client/src/main/java/com/tigrisdata/db/client/TigrisAsyncClient.java
- client/src/main/java/com/tigrisdata/db/client/TigrisClient.java
- client/src/main/java/com/tigrisdata/db/client/TypeConverter.java
- client/src/test/java/com/tigrisdata/db/client/StandardTigrisAsyncClientTest.java
- client/src/test/java/com/tigrisdata/db/client/StandardTigrisClientTest.java
- client/src/test/java/com/tigrisdata/db/client/grpc/TestUserService.java
- updated API
- implemented server metadata method.
> feat: Implemented getServerMetadata method

- client/pom.xml
- pom.xml
- schema-generator/pom.xml
- schema-generator/schema-generator-core/pom.xml
- types/pom.xml
Somehow the version got out of sync with last release. Fixing it.
> fix: Fixing out of sync version

- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncCollection.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncDatabase.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisCollection.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisDatabase.java
- client/src/main/java/com/tigrisdata/db/client/StandardTransactionSession.java
- client/src/main/java/com/tigrisdata/db/client/TigrisDatabase.java
- Fixed Javadoc warning.
- Restricted visibility of implementation classes.
> fix: Fixed Javadoc warning and improved visibility

- client/src/main/java/com/tigrisdata/db/client/InsertOrReplaceResponse.java
- client/src/main/java/com/tigrisdata/db/client/InsertResponse.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncCollection.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisCollection.java
- client/src/main/java/com/tigrisdata/db/client/TypeConverter.java
- client/src/test/java/com/tigrisdata/db/client/InsertOrReplaceResponseTest.java
- client/src/test/java/com/tigrisdata/db/client/InsertResponseTest.java
- client/src/test/java/com/tigrisdata/db/client/StandardTigrisAsyncCollectionTest.java
- client/src/test/java/com/tigrisdata/db/client/StandardTigrisCollectionTest.java
- client/src/test/java/com/tigrisdata/db/client/collection/User.java
- client/src/test/java/com/tigrisdata/db/client/grpc/TestUserService.java
Made the generated ids available in InsertResponse and InsertOrReplaceResponse.
> feat: Added generated IDs in response

- client/pom.xml
- pom.xml
- schema-generator/schema-generator-core/pom.xml
- types/pom.xml
- updated developers section in pom.xml (added @mattayres )
- updated jackson for security vulnerability
- updated gRPC
> chore: pom revisit + dependencies updates

- client/src/main/java/com/tigrisdata/db/client/TigrisCollection.java
- client/src/main/java/com/tigrisdata/db/client/search/FacetCount.java
- client/src/main/java/com/tigrisdata/db/client/search/FacetCountDistribution.java
- client/src/main/java/com/tigrisdata/db/client/search/FacetFieldsQuery.java
- client/src/main/java/com/tigrisdata/db/client/search/FacetQuery.java
- client/src/main/java/com/tigrisdata/db/client/search/FacetQueryOptions.java
- client/src/main/java/com/tigrisdata/db/client/search/FacetStats.java
- client/src/main/java/com/tigrisdata/db/client/search/Hit.java
- client/src/main/java/com/tigrisdata/db/client/search/Query.java
- client/src/main/java/com/tigrisdata/db/client/search/QueryString.java
- client/src/main/java/com/tigrisdata/db/client/search/SearchFields.java
- client/src/main/java/com/tigrisdata/db/client/search/SearchMeta.java
- client/src/main/java/com/tigrisdata/db/client/search/SearchRequest.java
- client/src/main/java/com/tigrisdata/db/client/search/SearchRequestOptions.java
- client/src/main/java/com/tigrisdata/db/client/search/SearchResult.java
- client/src/main/java/com/tigrisdata/db/client/search/SortOrder.java
- client/src/main/java/com/tigrisdata/db/client/search/package-info.java
- client/src/test/java/com/tigrisdata/db/client/search/FacetQueryOptionsTest.java
- client/src/test/java/com/tigrisdata/db/client/search/QueryStringTest.java
- Javadocs for /search builder classes
> docs: documentation for search related classes

- client/src/main/java/com/tigrisdata/db/client/AbstractTigrisCollection.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncCollection.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisCollection.java
- client/src/main/java/com/tigrisdata/db/client/TypeConverter.java
- client/src/main/java/com/tigrisdata/db/client/search/Hit.java
- client/src/main/java/com/tigrisdata/db/client/search/HitMeta.java
- client/src/main/java/com/tigrisdata/db/client/search/SearchMeta.java
- client/src/main/java/com/tigrisdata/db/client/search/SearchRequestOptions.java
- client/src/test/java/com/tigrisdata/db/client/TypeConverterTest.java
- client/src/test/java/com/tigrisdata/db/client/grpc/TestUserService.java
- client/src/test/java/com/tigrisdata/db/client/search/HitMetaTest.java
- client/src/test/java/com/tigrisdata/db/client/search/SearchMetaTest.java
- client/src/test/java/com/tigrisdata/db/client/search/SearchRequestOptionsTest.java
- Client implementation for latest tigris search API
- Search pagination support
- Search hit metadata support
> Search metadata and pagination support

- client/pom.xml
mainly due to https://github.com/grpc/grpc-java/issues/8311
> fix: Upgraded dependencies

- client/src/main/java/com/tigrisdata/db/client/AbstractTigrisCollection.java
- client/src/main/java/com/tigrisdata/db/client/AbstractTigrisDatabase.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncClient.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncDatabase.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisDatabase.java
- client/src/main/java/com/tigrisdata/db/client/StandardTransactionSession.java
- client/src/main/java/com/tigrisdata/db/client/TigrisCallCredentialOauth2.java
- client/src/main/java/com/tigrisdata/db/client/TypeConverter.java
- client/src/test/java/com/tigrisdata/db/client/StandardTigrisAsyncClientTest.java
- client/src/test/java/com/tigrisdata/db/client/StandardTigrisAsyncDatabaseTest.java
- client/src/test/java/com/tigrisdata/db/client/TransactionSessionTest.java
- client/src/test/java/com/tigrisdata/db/client/TransactionalTigrisCollectionTest.java
- client/src/test/java/com/tigrisdata/db/client/grpc/ContextSettingServerInterceptor.java
- client/src/test/java/com/tigrisdata/db/client/grpc/CookieSetterServerInterceptor.java
- client/src/test/java/com/tigrisdata/db/client/grpc/TransactionTestTigrisService.java
- Handling response cookie for interactive transactions.
- Misc code cleanup.
> feat: Handling response cookie for interactive transactions

- client/src/main/java/com/tigrisdata/db/client/OAuth2TokenService.java
- client/src/main/java/com/tigrisdata/db/client/TigrisCallCredentialOauth2.java
- client/src/main/java/com/tigrisdata/db/client/Utilities.java
- client/src/main/java/com/tigrisdata/db/client/config/TigrisConfiguration.java
- client/src/test/java/com/tigrisdata/db/client/TestUtils.java
- client/src/test/java/com/tigrisdata/db/client/config/TigrisConfigurationTest.java
Tigris server [will support](https://github.com/tigrisdata/tigris/pull/441) application based client credentials for authentication and authorization. This PR updates the client support to adapt to that mechanism.
> feat: Support application authentication

- client/pom.xml
- schema-generator/schema-generator-core/pom.xml
motivation https://sbom.lift.sonatype.com/report/T1-a0368c8f29fdaa555824-7f32f6de2efd45-1661381219-5cbb6f63819a4bd9991b72fef56e9b70
> chore: Updated dependencies

- client/pom.xml
- pom.xml
- tigris-spring-boot-autoconfigure/README.md
- tigris-spring-boot-autoconfigure/pom.xml
- tigris-spring-boot-autoconfigure/src/main/java/com/tigrisdata/spring/autoconfigure/TigrisAsyncSpringAutoConfiguration.java
- tigris-spring-boot-autoconfigure/src/main/java/com/tigrisdata/spring/autoconfigure/TigrisSpringAutoConfiguration.java
- tigris-spring-boot-autoconfigure/src/main/java/com/tigrisdata/spring/autoconfigure/TigrisUtilities.java
- tigris-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
- tigris-spring-boot-autoconfigure/src/test/java/com/tigrisdata/spring/autoconfigure/TigrisSpringAutoConfigurationTest.java
- types/pom.xml
- Added Spring boot autoconfiguration.
- Upgraded jackson library to strengthen security.
> feat: Added Tigris spring autoconfiguration

- client/src/main/java/com/tigrisdata/db/client/ReadRequestOptions.java
- client/src/test/java/com/tigrisdata/db/client/ReadRequestOptionsTest.java
- tigris-spring-boot-autoconfigure/README.md
- tigris-spring-boot-autoconfigure/src/main/java/com/tigrisdata/spring/autoconfigure/TigrisAsyncInitializer.java
- tigris-spring-boot-autoconfigure/src/main/java/com/tigrisdata/spring/autoconfigure/TigrisAsyncSpringAutoConfiguration.java
- tigris-spring-boot-autoconfigure/src/main/java/com/tigrisdata/spring/autoconfigure/TigrisInitializer.java
- tigris-spring-boot-autoconfigure/src/main/java/com/tigrisdata/spring/autoconfigure/TigrisSpringAutoConfiguration.java
- Added initializer in auto configurer.
- Simplified ReadRequestOptions.
> feat: Simplified auto-configurer module

- client/src/main/java/com/tigrisdata/db/client/DatabaseDescription.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisAsyncDatabase.java
- client/src/main/java/com/tigrisdata/db/client/StandardTigrisDatabase.java
- client/src/main/java/com/tigrisdata/db/client/StandardTransactionSession.java
- client/src/main/java/com/tigrisdata/db/client/TypeConverter.java
- client/src/test/java/com/tigrisdata/db/client/StandardTigrisAsyncDatabaseTest.java
- client/src/test/java/com/tigrisdata/db/client/StandardTigrisDatabaseTest.java
- client/src/test/java/com/tigrisdata/db/client/TypeConverterTest.java
- client/src/test/java/com/tigrisdata/db/client/grpc/AuthEnabledTestTigrisService.java
- client/src/test/java/com/tigrisdata/db/client/grpc/FailingTestTigrisService.java
- client/src/test/java/com/tigrisdata/db/client/grpc/TestTigrisService.java
- client/src/test/java/com/tigrisdata/db/client/grpc/TransactionTestTigrisService.java
See https://github.com/tigrisdata/tigris-api/pull/159
> refactor! [BREAKING] Switching to Project paradigm

- client/src/main/java/com/tigrisdata/db/client/TypeConverter.java
- client/src/test/java/com/tigrisdata/db/client/grpc/TestTigrisService.java
Implement https://github.com/tigrisdata/tigris-api/pull/168
> refactor: DatabaseMetadata and ProjectMetadata

- client/pom.xml
- client/src/main/java/com/tigrisdata/db/client/config/TigrisConfiguration.java
- types/pom.xml
Added support for Kotlin in Jackson and upgraded Jackson set of libraries.
> fix: Added jackson-kotlin module
